import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className="bg-white-800">
      <Head>
        <title>Auction Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <footer>
        <h3 className="text-white">Footer</h3>
      </footer>
    </div>
  )
}

export default Home
